### ISSUE TITLE
Version 1.1.9: "_.keyBy is not a function" error because incorrect lodash version is installed

### ISSUE THREAD

**Issue by NickAdriaenssens** [dpa99c/cordova-custom-config#22]
Please change the package.json so the plugin will install at least lodash 4.0.0. 
I had to rollback to version 1.1.8 because I got ```cordova-custom-config: Error updating config for platform 'android': _.keyBy is not a function```, same for ios. The plugin installed lodash 3.10.1.

**Comment by dpa99c** [comment]
The plugin doesn't specify a version of lodash as you can see in the [package.json](https://github.com/dpa99c/cordova-custom-config/blob/master/package.json#L40). The reason is that dependencies specified in the package.json are not automatically installed when a cordova plugin is installed into a project, therefore this plugin has to rely on a [custom hook script](https://github.com/dpa99c/cordova-custom-config/blob/master/hooks/resolveDependencies.js) to replicate the programmatic installation performed by `npm install`. 

Currently this script doesn't read the version specified in the package.json, only the package name. The reason for that is because specifying a version number in the form `npm install foo@x.y.z` causes the CLI command to return before it has finished downloading and installing the specified module, causing a race condition in the code. Omitting it and using `npm install foo` does not cause this issue. I would like to fix the version numbers to prevent the next backwardly-incompatible dependency release breaking the plugin again, but need to overcome this race condition issue first.

The reason you have `lodash@3.10.1` is most likely because the plugin was installed prior to release of `lodash@4.0.0`. Without the ability to specify a package version in the dependency resolution script, the best I can do for now is to feature-detect `keyBy` vs `indexBy` and use the method that exists in the currently installed lodash version. I'll do this when I have some time.

**Comment by dpa99c** [comment]
Fixed by https://github.com/dpa99c/cordova-custom-config/commit/f3224c3c6a440cd652fb29e49877428e75ccfd81

**Comment by NickAdriaenssens** [comment]
Thanks for the quick response!

**Comment by oak-tree** [comment]
upgraded to lastet version 1.1.10
but still gets 
cordova-custom-config: Error updating config for platform 'android': keyBy is not a function
cordova-custom-config: Error updating config for platform 'ios': keyBy is not a function

**Comment by mykthex** [comment]
I also get the same errors as oak-tree. Last version of cordova-custom-config and last version of lodash.

**Comment by IvanKarpan** [comment]
Same... does not work :( Too bad I can't switch from a custom hook to this plugin.
